name: Sync to Prod Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    name: Push to omnihub-prod/dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OmniHub code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug PAT
        run: |
          if [ -z "${{ secrets.PROD_REPO_PAT }}" ]; then
            echo "PAT is EMPTY!"
          else
            echo "PAT length: ${#PAT}"
            echo "PAT starts with: ${PAT:0:4}"
          fi
        env:
          PAT: ${{ secrets.PROD_REPO_PAT }}

      - name: Push to omnihub-prod dev branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote add prod "https://x-access-token:${PAT}@github.com/Boopathiraja4264/omnihub-prod"
          git push -u prod main:dev --force
        env:
          PAT: ${{ secrets.PROD_REPO_PAT }}
